---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-operator-ca
  namespace: openshift-machine-api
  labels:
    k8s-app: cluster-autoscaler-operator
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
data:
